### ISSUE TITLE
Change permissions for the configuration routes

### ISSUE THREAD

**Issue by jrearick-pfg** [pantheon-systems/pantheon_domain_masking#10]
The routes for the configuration pages use the permission `access administration pages`. There's a lot of sites out there that grant this permission to roles that maybe shouldn't have the ability to alter these settings. Perhaps it's more appropriate to use `administer site configuration` which has the extra warning to only give to trusted roles?

**Comment by kpaxman** [comment]
I feel fairly certain I did that wrong, but at least there's something to look at :)

**Comment by lkmorlan** [comment]
The patch is fine. It is just that the merge request is against the fork instead of the original.

**Comment by jspellman814** [comment]
Closing issue as the associated PR (#23) has been merged.

**Comment by namespacebrian** [comment]
As some people who had permissions before will no longer have them after this update, if the change ends up bothering anyone, I'll just point at everyone in this ticket ;)

![Gates Ballmer](https://c.tenor.com/l3Ft21whp0QAAAAd/bill-gates-steve-ballmer.gif)

**Comment by jrearick-pfg** [comment]
I guess that would be all my fault 😬 /sarcasm

**Comment by jrearick-pfg** [comment]
Any word on when this would hit packagist? Will there need to be a "release"?

**Comment by jspellman814** [comment]
@jrearick-pfg I've created a new tag, [1.0.1](https://github.com/pantheon-systems/pantheon_domain_masking/releases/tag/1.0.1), which should be available through packagist shortly.

**Comment by jrearick-pfg** [comment]
Thanks for the bump, but I'm not seeing 1.0.1 out there yet https://packagist.org/packages/pantheon-systems/pantheon_domain_masking

**Comment by jspellman814** [comment]
@jrearick-pfg Apologies for the delay - it's available now: https://packagist.org/packages/pantheon-systems/pantheon_domain_masking#1.0.1
