### ISSUE TITLE
Use semantic versioning and tags

### ISSUE THREAD

**Issue by lkmorlan** [pantheon-systems/pantheon_domain_masking#15]
Move development to a 1.0.x branch and tag releases. This would make it easier to manage in Composer.

**Comment by namespacebrian** [comment]
A 1.0.0 tag has been created and is recognized by packagist.org: https://packagist.org/packages/pantheon-systems/pantheon_domain_masking

I believe that addresses the idea/request here, so I'm closing this issue.  Re-open if there's something missing..

**Comment by lkmorlan** [comment]
It would be nice if the development branch was renamed to 1.0.x.
