### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by namespacebrian** [pantheon-systems/pantheon_domain_masking#20]
`pantheon-systems/pantheon_domain_masking` version 1.0, 1.0.1, etc..

Prompted by the composer package name changing as a result of #18, I noticed that the only 'version' of the module is currently 'dev-master'.  I'm not sure if establishing versions would actually have prevented that from being a breaking change, but establishing versions may help limit the scope of potentially breaking changes in the future.

**Comment by greg-1-anderson** [comment]
Folks have been using this as a stable module for a while. Tagged 1.0.0.
