### ISSUE TITLE
Domain masking module misbehaving if subpath setting is in the URL alias

### ISSUE THREAD

**Issue by jamesgrobertson** [pantheon-systems/pantheon_domain_masking#24]
On the Pantheon platform, if the string that is in the `subpath` setting also exists in the URL alias, then the subpath is excluded from all other Drupal-generated URLs.

For example, if the setting is set to `subpath`, then on `www.example.com/subpath/subpath-in-alias`, any other link that Drupal generates on the page follows the pattern `www.example.com/no-subpath-in-alias` (instead of `www.example.com/subpath/no-subpath-in-alias`). 

Also, if a user is logged in on that path, then they do not see any part of the page that authenticated users can see like the toolbar, primary tabs, etc.

**Comment by jamesgrobertson** [comment]
It seems to only happen if the subpath setting string is the first word in the alias, i.e. it happens when the url is `www.example.com/subpath/subpath-first` versus `www.example.com/subpath/second-subpath`.

**Comment by kporras07** [comment]
No longer needed as per closing comment in #25 

Thanks for the report and PR.
